// Code generated by protoc-gen-go. DO NOT EDIT.
// source: restaurant.proto

package restaurant

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RestaurantRequest struct {
	Id      int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rating  float32 `protobuf:"fixed32,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Cusines string  `protobuf:"bytes,4,opt,name=cusines,proto3" json:"cusines,omitempty"`
	Address string  `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	// message timing{
	//     message time{
	//         int32 hr = 1;
	//         int32 min = 2;
	//     }
	//     time starttime=1;
	//     time endtime=2;
	// }
	// timing times = 6;
	Starttime            string   `protobuf:"bytes,6,opt,name=starttime,proto3" json:"starttime,omitempty"`
	Endtime              string   `protobuf:"bytes,7,opt,name=endtime,proto3" json:"endtime,omitempty"`
	Cft                  float32  `protobuf:"fixed32,8,opt,name=cft,proto3" json:"cft,omitempty"`
	ImgUrl               string   `protobuf:"bytes,9,opt,name=img_url,json=imgUrl,proto3" json:"img_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestaurantRequest) Reset()         { *m = RestaurantRequest{} }
func (m *RestaurantRequest) String() string { return proto.CompactTextString(m) }
func (*RestaurantRequest) ProtoMessage()    {}
func (*RestaurantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9528536a6390faa1, []int{0}
}

func (m *RestaurantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestaurantRequest.Unmarshal(m, b)
}
func (m *RestaurantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestaurantRequest.Marshal(b, m, deterministic)
}
func (m *RestaurantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestaurantRequest.Merge(m, src)
}
func (m *RestaurantRequest) XXX_Size() int {
	return xxx_messageInfo_RestaurantRequest.Size(m)
}
func (m *RestaurantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestaurantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestaurantRequest proto.InternalMessageInfo

func (m *RestaurantRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RestaurantRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RestaurantRequest) GetRating() float32 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *RestaurantRequest) GetCusines() string {
	if m != nil {
		return m.Cusines
	}
	return ""
}

func (m *RestaurantRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *RestaurantRequest) GetStarttime() string {
	if m != nil {
		return m.Starttime
	}
	return ""
}

func (m *RestaurantRequest) GetEndtime() string {
	if m != nil {
		return m.Endtime
	}
	return ""
}

func (m *RestaurantRequest) GetCft() float32 {
	if m != nil {
		return m.Cft
	}
	return 0
}

func (m *RestaurantRequest) GetImgUrl() string {
	if m != nil {
		return m.ImgUrl
	}
	return ""
}

type RestaurantResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestaurantResponse) Reset()         { *m = RestaurantResponse{} }
func (m *RestaurantResponse) String() string { return proto.CompactTextString(m) }
func (*RestaurantResponse) ProtoMessage()    {}
func (*RestaurantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9528536a6390faa1, []int{1}
}

func (m *RestaurantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestaurantResponse.Unmarshal(m, b)
}
func (m *RestaurantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestaurantResponse.Marshal(b, m, deterministic)
}
func (m *RestaurantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestaurantResponse.Merge(m, src)
}
func (m *RestaurantResponse) XXX_Size() int {
	return xxx_messageInfo_RestaurantResponse.Size(m)
}
func (m *RestaurantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RestaurantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RestaurantResponse proto.InternalMessageInfo

func (m *RestaurantResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type EmptyParam struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EmptyParam) Reset()         { *m = EmptyParam{} }
func (m *EmptyParam) String() string { return proto.CompactTextString(m) }
func (*EmptyParam) ProtoMessage()    {}
func (*EmptyParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_9528536a6390faa1, []int{2}
}

func (m *EmptyParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EmptyParam.Unmarshal(m, b)
}
func (m *EmptyParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EmptyParam.Marshal(b, m, deterministic)
}
func (m *EmptyParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EmptyParam.Merge(m, src)
}
func (m *EmptyParam) XXX_Size() int {
	return xxx_messageInfo_EmptyParam.Size(m)
}
func (m *EmptyParam) XXX_DiscardUnknown() {
	xxx_messageInfo_EmptyParam.DiscardUnknown(m)
}

var xxx_messageInfo_EmptyParam proto.InternalMessageInfo

func init() {
	proto.RegisterType((*RestaurantRequest)(nil), "restaurant.RestaurantRequest")
	proto.RegisterType((*RestaurantResponse)(nil), "restaurant.RestaurantResponse")
	proto.RegisterType((*EmptyParam)(nil), "restaurant.empty_param")
}

func init() { proto.RegisterFile("restaurant.proto", fileDescriptor_9528536a6390faa1) }

var fileDescriptor_9528536a6390faa1 = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x6d, 0xd2, 0x36, 0x35, 0x23, 0x95, 0x38, 0x07, 0xbb, 0x14, 0x95, 0x92, 0x53, 0x0f, 0x52,
	0x44, 0x3f, 0x41, 0xc1, 0x83, 0xb7, 0x94, 0x9e, 0xcb, 0xda, 0x8c, 0x65, 0xa1, 0xbb, 0x8d, 0xbb,
	0x93, 0x83, 0x7f, 0xea, 0x17, 0xf8, 0x1d, 0x92, 0x6d, 0x34, 0x0b, 0xa2, 0xa7, 0xde, 0xe6, 0xcd,
	0x9b, 0x37, 0xfb, 0xde, 0xb0, 0x90, 0x59, 0x72, 0x2c, 0x6b, 0x2b, 0x0d, 0x2f, 0x2a, 0xbb, 0xe7,
	0x3d, 0x42, 0xd7, 0xc9, 0x3f, 0x23, 0x38, 0x2f, 0x7e, 0x60, 0x41, 0x6f, 0x35, 0x39, 0xc6, 0x33,
	0x88, 0x55, 0x29, 0xa2, 0x59, 0x34, 0x1f, 0x16, 0xb1, 0x2a, 0x11, 0x61, 0x60, 0xa4, 0x26, 0x11,
	0xcf, 0xa2, 0x79, 0x5a, 0xf8, 0x1a, 0x2f, 0x20, 0xb1, 0x92, 0x95, 0xd9, 0x8a, 0xfe, 0x2c, 0x9a,
	0xc7, 0x45, 0x8b, 0x50, 0xc0, 0x68, 0x53, 0x3b, 0x65, 0xc8, 0x89, 0x81, 0x1f, 0xff, 0x86, 0x0d,
	0x23, 0xcb, 0xd2, 0x92, 0x73, 0x62, 0x78, 0x60, 0x5a, 0x88, 0x97, 0x90, 0x3a, 0x96, 0x96, 0x59,
	0x69, 0x12, 0x89, 0xe7, 0xba, 0x46, 0xa3, 0x23, 0x53, 0x7a, 0x6e, 0x74, 0xd0, 0xb5, 0x10, 0x33,
	0xe8, 0x6f, 0x5e, 0x59, 0x9c, 0x78, 0x03, 0x4d, 0x89, 0x13, 0x18, 0x29, 0xbd, 0x5d, 0xd7, 0x76,
	0x27, 0x52, 0x3f, 0x9b, 0x28, 0xbd, 0x5d, 0xd9, 0x5d, 0x7e, 0x03, 0x18, 0xe6, 0x74, 0xd5, 0xde,
	0x38, 0x1f, 0xc2, 0xb1, 0xe4, 0xda, 0xf9, 0xb0, 0x69, 0xd1, 0xa2, 0x7c, 0x0c, 0xa7, 0xa4, 0x2b,
	0x7e, 0x5f, 0x57, 0xd2, 0x4a, 0x7d, 0xf7, 0x11, 0x03, 0x74, 0x6a, 0x5c, 0x42, 0xf6, 0x60, 0x49,
	0x32, 0x05, 0xbd, 0xab, 0x45, 0x70, 0xe7, 0x5f, 0x17, 0x9d, 0x5e, 0xff, 0x45, 0x1f, 0x8c, 0xe4,
	0x3d, 0x7c, 0x86, 0xf1, 0x13, 0x71, 0xb0, 0x71, 0x12, 0x4a, 0x02, 0x37, 0xd3, 0xff, 0x9f, 0xca,
	0x7b, 0xb7, 0x51, 0xe3, 0x70, 0x55, 0x95, 0x47, 0x76, 0xb8, 0x84, 0xec, 0x91, 0x76, 0x74, 0xd4,
	0xa5, 0x2f, 0x89, 0xff, 0x93, 0xf7, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x20, 0x8c, 0x06,
	0xa7, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RestaurantClient is the client API for Restaurant service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RestaurantClient interface {
	CreateRestaurant(ctx context.Context, in *RestaurantRequest, opts ...grpc.CallOption) (*RestaurantResponse, error)
	GetRestaurant(ctx context.Context, in *EmptyParam, opts ...grpc.CallOption) (Restaurant_GetRestaurantClient, error)
	UpdateRestaurant(ctx context.Context, in *RestaurantRequest, opts ...grpc.CallOption) (*RestaurantResponse, error)
	DeleteRestaurant(ctx context.Context, in *RestaurantRequest, opts ...grpc.CallOption) (*RestaurantResponse, error)
}

type restaurantClient struct {
	cc *grpc.ClientConn
}

func NewRestaurantClient(cc *grpc.ClientConn) RestaurantClient {
	return &restaurantClient{cc}
}

func (c *restaurantClient) CreateRestaurant(ctx context.Context, in *RestaurantRequest, opts ...grpc.CallOption) (*RestaurantResponse, error) {
	out := new(RestaurantResponse)
	err := c.cc.Invoke(ctx, "/restaurant.Restaurant/CreateRestaurant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantClient) GetRestaurant(ctx context.Context, in *EmptyParam, opts ...grpc.CallOption) (Restaurant_GetRestaurantClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Restaurant_serviceDesc.Streams[0], "/restaurant.Restaurant/GetRestaurant", opts...)
	if err != nil {
		return nil, err
	}
	x := &restaurantGetRestaurantClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Restaurant_GetRestaurantClient interface {
	Recv() (*RestaurantRequest, error)
	grpc.ClientStream
}

type restaurantGetRestaurantClient struct {
	grpc.ClientStream
}

func (x *restaurantGetRestaurantClient) Recv() (*RestaurantRequest, error) {
	m := new(RestaurantRequest)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *restaurantClient) UpdateRestaurant(ctx context.Context, in *RestaurantRequest, opts ...grpc.CallOption) (*RestaurantResponse, error) {
	out := new(RestaurantResponse)
	err := c.cc.Invoke(ctx, "/restaurant.Restaurant/UpdateRestaurant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantClient) DeleteRestaurant(ctx context.Context, in *RestaurantRequest, opts ...grpc.CallOption) (*RestaurantResponse, error) {
	out := new(RestaurantResponse)
	err := c.cc.Invoke(ctx, "/restaurant.Restaurant/DeleteRestaurant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RestaurantServer is the server API for Restaurant service.
type RestaurantServer interface {
	CreateRestaurant(context.Context, *RestaurantRequest) (*RestaurantResponse, error)
	GetRestaurant(*EmptyParam, Restaurant_GetRestaurantServer) error
	UpdateRestaurant(context.Context, *RestaurantRequest) (*RestaurantResponse, error)
	DeleteRestaurant(context.Context, *RestaurantRequest) (*RestaurantResponse, error)
}

// UnimplementedRestaurantServer can be embedded to have forward compatible implementations.
type UnimplementedRestaurantServer struct {
}

func (*UnimplementedRestaurantServer) CreateRestaurant(ctx context.Context, req *RestaurantRequest) (*RestaurantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRestaurant not implemented")
}
func (*UnimplementedRestaurantServer) GetRestaurant(req *EmptyParam, srv Restaurant_GetRestaurantServer) error {
	return status.Errorf(codes.Unimplemented, "method GetRestaurant not implemented")
}
func (*UnimplementedRestaurantServer) UpdateRestaurant(ctx context.Context, req *RestaurantRequest) (*RestaurantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRestaurant not implemented")
}
func (*UnimplementedRestaurantServer) DeleteRestaurant(ctx context.Context, req *RestaurantRequest) (*RestaurantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRestaurant not implemented")
}

func RegisterRestaurantServer(s *grpc.Server, srv RestaurantServer) {
	s.RegisterService(&_Restaurant_serviceDesc, srv)
}

func _Restaurant_CreateRestaurant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestaurantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServer).CreateRestaurant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/restaurant.Restaurant/CreateRestaurant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServer).CreateRestaurant(ctx, req.(*RestaurantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Restaurant_GetRestaurant_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(EmptyParam)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RestaurantServer).GetRestaurant(m, &restaurantGetRestaurantServer{stream})
}

type Restaurant_GetRestaurantServer interface {
	Send(*RestaurantRequest) error
	grpc.ServerStream
}

type restaurantGetRestaurantServer struct {
	grpc.ServerStream
}

func (x *restaurantGetRestaurantServer) Send(m *RestaurantRequest) error {
	return x.ServerStream.SendMsg(m)
}

func _Restaurant_UpdateRestaurant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestaurantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServer).UpdateRestaurant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/restaurant.Restaurant/UpdateRestaurant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServer).UpdateRestaurant(ctx, req.(*RestaurantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Restaurant_DeleteRestaurant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestaurantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServer).DeleteRestaurant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/restaurant.Restaurant/DeleteRestaurant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServer).DeleteRestaurant(ctx, req.(*RestaurantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Restaurant_serviceDesc = grpc.ServiceDesc{
	ServiceName: "restaurant.Restaurant",
	HandlerType: (*RestaurantServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRestaurant",
			Handler:    _Restaurant_CreateRestaurant_Handler,
		},
		{
			MethodName: "UpdateRestaurant",
			Handler:    _Restaurant_UpdateRestaurant_Handler,
		},
		{
			MethodName: "DeleteRestaurant",
			Handler:    _Restaurant_DeleteRestaurant_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetRestaurant",
			Handler:       _Restaurant_GetRestaurant_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "restaurant.proto",
}
